default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres
  url: postgresql://127.0.0.1:5432

development:
  <<: *default
  database: myrecipes_development

test:
  <<: *default
  database: myrecipes_test

production:
  <<: *default
  database: myrecipes
  username: <%= ENV['MYRECIPES_DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['MYRECIPES_DATABASE_PASSWORD'] || 'postgres' %>
